services:
  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - "d:/clickhouse_database:/var/lib/clickhouse"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: always
  # main:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - "clickhouse"
  #   links:
  #     - "clickhouse"
